### ISSUE TITLE
Maui.Graphics.Controls

### ISSUE THREAD

**Issue by zigzag312** [jonathanpeppers/lols#3]
It would be interesting to see how Maui.Graphics.Controls performs as it's similar (as I understand it) to Flutter.

**Comment by jonathanpeppers** [comment]
PRs welcome!

I would tailor it a bit like this:

https://github.com/jonathanpeppers/lols/blob/canvas/src/android/LolsView.cs

If you can make a new project with a graphics view (whatever that is), and then draw each lol in a loop.

The issue is I got ~152,661 per second with the above sample -- and then the UI thread just renders at 60 fps. So I'm not sure how valid drawing APIs are for this test.

**Comment by zigzag312** [comment]
You're right. I took a quick look at benchmarks source just now, and I must admit, I'm not sure what exactly is being measured. 

I thought it would be interesting to see how much overhead do MAUI's native controls have (due to Java interop, memory marshaling...), compared to self drawn controls of Maui.Graphics.Controls.

**Comment by jonathanpeppers** [comment]
@zigzag312 if there is a Maui.Graphics alternative to `Label`, maybe it could be compared to that?

Otherwise, maybe you could compare something self-drawn vs a built-in control?

**Comment by zigzag312** [comment]
@jonathanpeppers It seems `Label` isn't yet implemented: https://github.com/dotnet/Microsoft.Maui.Graphics.Controls/issues/52

I haven't used Maui.Graphics.Controls yet, as it's still just an experiment, but I'm following it, as I'm highly interested in a cross platform UI library with a lower level customizability.
